# Makefile fragment for generating the TypsScript types from selected PHP classes.
#
# Needed:
#
# ABSBUILDDIR
# ABSSRCDIR
# APP_NAMESPACE
# SCSS_VARIABLES_DIR
# TS_PHP_SOURCE_DIRS
# TS_TYPES_DIR
# TYPESCRIPT_CONVERTER
#

PRETTIER_FORMATTER = $(ABSSRCDIR)/node_modules/.bin/prettier
ESLINT = $(ABSSRCDIR)/node_modules/.bin/eslint

TS_TYPES_FILES = $(TS_TYPES_DIR)/php-types.d.ts $(TS_TYPES_DIR)/php-modules/ROOT.ts
PHP_SOURCES=$(TS_PHP_SOURCE_DIRS:%=--source-dir %)
TS_TYPES_FILES_DEPS = $(foreach dir,$(TS_PHP_SOURCE_DIRS),$(shell find $(dir) -name "*.php"))

#@private
$(TS_TYPES_FILES): $(TS_TYPES_FILES_DEPS) $(TYPESCRIPT_CONVERTER) $(wildcard $(ABSSRCDIR)/dev-scripts/lib/scripts/php-to-typescript/*.php) $(MAKEFILE_DEP)
	$(MAKE) dev-setup
	$(TYPESCRIPT_CONVERTER) --output-prefix=$(TS_TYPES_DIR) $(PHP_SOURCES) --as-modules --ns-prefix='OCA\$(APP_NAMESPACE)' --scoped-ns-prefix=$(WRAPPER_NAMESPACE_POSTFIX)
	$(PRETTIER_FORMATTER) --write --ignore-path /dev/null $(TS_TYPES_DIR)
	[ -x "$(ESLINT)" ] && $(ESLINT) $(TS_TYPES_DIR)

#@private
ts-types-files: $(TS_TYPES_FILES)
# @echo $(TS_TYPE_FILES)
# @echo $(TS_TYPE_FILES_DEPS)
.PHONY: ts-types-files

#@private
scss-variables: $(TS_TYPES_FILES)
	for i in $$(find $(TS_TYPES_DIR)/php-modules/ -name "*CssClasses.ts"); do\
 SUB_DIR="$$(dirname $$i|sed 's|^$(TS_TYPES_DIR)/php-modules/||g')";\
 mkdir -p "$(SCSS_VARIABLES_DIR)/$$SUB_DIR";\
 SCSS_FILE="$$SUB_DIR/$$(basename $$i .ts).scss";\
 TS_FILE="$$(echo $$i|sed 's|^$(ABSBUILDDIR)|build|g')";\
 echo "Generating $$SCSS_FILE from $$TS_FILE";\
 echo -e "/** Autogenerated from $$TS_FILE, do not edit! */\n" > "$(SCSS_VARIABLES_DIR)/$$SCSS_FILE";\
 grep 'export const' $$i|\
  sed -E\
   -e 's/export const ([^= ]+)\s*=\s*'"'([^']+)'"'/$$\1_CSS_CLASS: "\2"/g'\
   -e 's/([A-Z])([A-Z]+)(_|(:))/\1\L\2\4/g'\
   -e 's/^(\$$[A-Z])/\L\1/g' >> "$(SCSS_VARIABLES_DIR)/$$SCSS_FILE";\
 done
.PHONY: scss-variables
