# Makefile fragment for generating the TypsScript types from selected PHP classes.
#
# Needed:
#
# ABSBUILDDIR
# ABSSRCDIR
# APP_NAMESPACE
# SCSS_VARIABLES_DIR
# TS_TYPES_DIR
# TYPESCRIPT_CONVERTER
#

PRETTIER_FORMATTER = $(ABSSRCDIR)/node_modules/.bin/prettier
ESLINT = $(ABSSRCDIR)/node_modules/.bin/eslint

ifeq (,$(findstring print_ts_type_files,$(MAKECMDGOALS))$(findstring clean,$(MAKECMDGOALS)))
TS_TYPE_FILES=$(shell make NO_STDOUT=1 --debug=none --silent print_ts_type_files)
TS_TYPE_FILES_DEPS=$(shell make NO_STDOUT=1 --debug=none --silent print_ts_type_files_deps)
else ifeq (clean, $(findstring clean,$(MAKECMDGOALS)))
# ok
else ifeq (,$(subst print_ts_type_files_deps,,$(MAKECMDGOALS)))
# ok
else ifeq (,$(subst print_ts_type_files,,$(MAKECMDGOALS)))
# ok
else
$(error print_ts_type_files[_deps] needs to be the only target, but I got the following targets: $(MAKECMDGOALS))
endif

#@private
print_ts_type_files: app-toolkit composer.lock
	echo $(addprefix $(TS_TYPES_DIR)/, $(shell $(TYPESCRIPT_CONVERTER) --outputs))
.PHONY: print_ts_type_files_deps

#@private
print_ts_type_files_deps: app-toolkit composer.lock
	echo $$(for i in $(addprefix $(ABSSRCDIR)/, $(shell $(TYPESCRIPT_CONVERTER) --sources)); do { [ -d $$i ] && find $$i -name "*.php"; } || echo $$i ; done)
.PHONY: print_ts_type_files_deps

#@private
$(TS_TYPE_FILES): $(TS_TYPE_FILES_DEPS) $(TYPESCRIPT_CONVERTER) $(wildcard $(ABSSRCDIR)/dev-scripts/lib/scripts/php-to-typescript/*.php) Makefile
	$(TYPESCRIPT_CONVERTER) --output-prefix=$(TS_TYPES_DIR) --source-prefix=$(ABSSRCDIR) --as-modules --ns-prefix='OCA\$(APP_NAMESPACE)' --scoped-ns-prefix=$(WRAPPER_NAMESPACE_POSTFIX)
	$(PRETTIER_FORMATTER) --write --ignore-path /dev/null $(TS_TYPES_DIR)
	[ -x "$(ESLINT)" ] && $(ESLINT) $(TS_TYPES_DIR)

#@private
ts-type-files: $(TS_TYPE_FILES)
# @echo $(TS_TYPE_FILES)
# @echo $(TS_TYPE_FILES_DEPS)
.PHONY: ts-type-files

#@private
scss-variables: $(TS_TYPE_FILES)
	for i in $$(find $(TS_TYPES_DIR)/php-modules/ -name "*CssClasses.ts"); do\
 SUB_DIR="$$(dirname $$i|sed 's|^$(TS_TYPES_DIR)/php-modules/||g')";\
 mkdir -p "$(SCSS_VARIABLES_DIR)/$$SUB_DIR";\
 SCSS_FILE="$$SUB_DIR/$$(basename $$i .ts).scss";\
 TS_FILE="$$(echo $$i|sed 's|^$(ABSBUILDDIR)|build|g')";\
 echo "Generating $$SCSS_FILE from $$TS_FILE";\
 echo -e "/** Autogenerated from $$TS_FILE, do not edit! */\n" > "$(SCSS_VARIABLES_DIR)/$$SCSS_FILE";\
 grep 'export const' $$i|\
  sed -E\
   -e 's/export const ([^= ]+)\s*=\s*'"'([^']+)'"'/$$\1_CSS_CLASS: "\2"/g'\
   -e 's/([A-Z])([A-Z]+)(_|(:))/\1\L\2\4/g'\
   -e 's/^(\$$[A-Z])/\L\1/g' >> "$(SCSS_VARIABLES_DIR)/$$SCSS_FILE";\
 done
.PHONY: scss-variables
